"""update messaging models

Revision ID: 4fd56b7f3dc6
Revises: eb920c09aad0
Create Date: 2026-05-10 20:09:58.961431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4fd56b7f3dc6'
down_revision: Union[str, Sequence[str], None] = 'eb920c09aad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversation_participants', 'last_read_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('conversations', sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('conversations', sa.Column('conversation_type', sa.String(), nullable=False))
    op.add_column('conversations', sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint(op.f('conversations_ticket_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'project', ['project_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'users', ['created_by'], ['id'])
    op.drop_column('conversations', 'ticket_id')
    op.drop_column('conversations', 'type')
    op.add_column('messages', sa.Column('message_type', sa.String(), nullable=False))
    op.add_column('messages', sa.Column('reply_to_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('messages', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('messages', 'edited_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_foreign_key(None, 'messages', 'messages', ['reply_to_id'], ['id'])
    op.drop_column('messages', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.alter_column('messages', 'edited_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('messages', 'deleted_at')
    op.drop_column('messages', 'reply_to_id')
    op.drop_column('messages', 'message_type')
    op.add_column('conversations', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('conversations', sa.Column('ticket_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_ticket_id_fkey'), 'conversations', 'tickets', ['ticket_id'], ['id'])
    op.drop_column('conversations', 'created_by')
    op.drop_column('conversations', 'conversation_type')
    op.drop_column('conversations', 'project_id')
    op.alter_column('conversation_participants', 'last_read_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
