"""add_completed_at_to_tickets

Revision ID: 59b3bd1a08ec
Revises: be0cfbfe1b41
Create Date: 2026-05-08 00:01:51.741640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59b3bd1a08ec'
down_revision: Union[str, Sequence[str], None] = 'be0cfbfe1b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'completed_at')
    # ### end Alembic commands ###
