"""improve schema performance and relational integrity

Revision ID: b4a7707e8766
Revises: 4fd56b7f3dc6
Create Date: 2026-05-12 16:31:05.867397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4a7707e8766'
down_revision: Union[str, Sequence[str], None] = '4fd56b7f3dc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachments', 'uploader_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_attachments_ticket_id'), 'attachments', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_attachments_uploader_id'), 'attachments', ['uploader_id'], unique=False)
    op.drop_constraint(op.f('attachments_ticket_id_fkey'), 'attachments', type_='foreignkey')
    op.drop_constraint(op.f('attachments_uploader_id_fkey'), 'attachments', type_='foreignkey')
    op.create_foreign_key(None, 'attachments', 'users', ['uploader_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'attachments', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.alter_column('comments', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_comments_ticket_id'), 'comments', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.drop_constraint(op.f('comments_ticket_id_fkey'), 'comments', type_='foreignkey')
    op.drop_constraint(op.f('comments_user_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('conversation_participants_conversation_id_fkey'), 'conversation_participants', type_='foreignkey')
    op.drop_constraint(op.f('conversation_participants_user_id_fkey'), 'conversation_participants', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_participants', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'conversation_participants', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_conversations_conversation_type'), 'conversations', ['conversation_type'], unique=False)
    op.create_index(op.f('ix_conversations_created_by'), 'conversations', ['created_by'], unique=False)
    op.create_index(op.f('ix_conversations_project_id'), 'conversations', ['project_id'], unique=False)
    op.drop_constraint(op.f('conversations_project_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('messages', 'sender_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_reply_to_id'), 'messages', ['reply_to_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.drop_constraint(op.f('messages_conversation_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_reply_to_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'messages', ['reply_to_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_project_owner_id'), 'project', ['owner_id'], unique=False)
    op.drop_constraint(op.f('project_members_project_id_fkey'), 'project_members', type_='foreignkey')
    op.drop_constraint(op.f('project_members_user_id_fkey'), 'project_members', type_='foreignkey')
    op.create_foreign_key(None, 'project_members', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_sprints_project_id'), 'sprints', ['project_id'], unique=False)
    op.create_index(op.f('ix_sprints_status'), 'sprints', ['status'], unique=False)
    op.drop_constraint(op.f('sprints_project_id_fkey'), 'sprints', type_='foreignkey')
    op.create_foreign_key(None, 'sprints', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_tickets_assignee_id'), 'tickets', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_tickets_reporter_id'), 'tickets', ['reporter_id'], unique=False)
    op.drop_constraint(op.f('tickets_assignee_id_fkey'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('tickets_parent_id_fkey'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('tickets_reporter_id_fkey'), 'tickets', type_='foreignkey')
    op.drop_constraint(op.f('tickets_project_id_fkey'), 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'users', ['reporter_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tickets', 'tickets', ['parent_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tickets', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tickets', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key(op.f('tickets_project_id_fkey'), 'tickets', 'project', ['project_id'], ['id'])
    op.create_foreign_key(op.f('tickets_reporter_id_fkey'), 'tickets', 'users', ['reporter_id'], ['id'])
    op.create_foreign_key(op.f('tickets_parent_id_fkey'), 'tickets', 'tickets', ['parent_id'], ['id'])
    op.create_foreign_key(op.f('tickets_assignee_id_fkey'), 'tickets', 'users', ['assignee_id'], ['id'])
    op.drop_index(op.f('ix_tickets_reporter_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assignee_id'), table_name='tickets')
    op.drop_constraint(None, 'sprints', type_='foreignkey')
    op.create_foreign_key(op.f('sprints_project_id_fkey'), 'sprints', 'project', ['project_id'], ['id'])
    op.drop_index(op.f('ix_sprints_status'), table_name='sprints')
    op.drop_index(op.f('ix_sprints_project_id'), table_name='sprints')
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.create_foreign_key(op.f('project_members_user_id_fkey'), 'project_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('project_members_project_id_fkey'), 'project_members', 'project', ['project_id'], ['id'])
    op.drop_index(op.f('ix_project_owner_id'), table_name='project')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(op.f('messages_reply_to_id_fkey'), 'messages', 'messages', ['reply_to_id'], ['id'])
    op.create_foreign_key(op.f('messages_conversation_id_fkey'), 'messages', 'conversations', ['conversation_id'], ['id'])
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_reply_to_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.alter_column('messages', 'sender_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_project_id_fkey'), 'conversations', 'project', ['project_id'], ['id'])
    op.drop_index(op.f('ix_conversations_project_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_created_by'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_conversation_type'), table_name='conversations')
    op.drop_constraint(None, 'conversation_participants', type_='foreignkey')
    op.drop_constraint(None, 'conversation_participants', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_participants_user_id_fkey'), 'conversation_participants', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('conversation_participants_conversation_id_fkey'), 'conversation_participants', 'conversations', ['conversation_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_user_id_fkey'), 'comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('comments_ticket_id_fkey'), 'comments', 'tickets', ['ticket_id'], ['id'])
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_ticket_id'), table_name='comments')
    op.alter_column('comments', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.create_foreign_key(op.f('attachments_uploader_id_fkey'), 'attachments', 'users', ['uploader_id'], ['id'])
    op.create_foreign_key(op.f('attachments_ticket_id_fkey'), 'attachments', 'tickets', ['ticket_id'], ['id'])
    op.drop_index(op.f('ix_attachments_uploader_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_ticket_id'), table_name='attachments')
    op.alter_column('attachments', 'uploader_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
