"""add owner role to project member table

Revision ID: ba7a28906776
Revises: 2f5c5d0737a3
Create Date: 2026-05-14 14:09:03.420054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba7a28906776'
down_revision: Union[str, Sequence[str], None] = '2f5c5d0737a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_members', 'role',
               existing_type=postgresql.ENUM('teamlead', 'member', 'viewer', name='project_role'),
               type_=sa.String(),
               nullable=False)
    op.create_index(op.f('ix_project_members_role'), 'project_members', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_members_role'), table_name='project_members')
    op.alter_column('project_members', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('teamlead', 'member', 'viewer', name='project_role'),
               nullable=True)
    # ### end Alembic commands ###
